/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.awt.Color;

/**
 *
 * @author giria
 */
public class User extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User.class.getName());

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userParentPanel = new javax.swing.JPanel();
        userSidePanel = new javax.swing.JPanel();
        mcUserLogo = new javax.swing.JLabel();
        manageUserLogo = new javax.swing.JLabel();
        systemUserLogo = new javax.swing.JLabel();
        userHome = new javax.swing.JButton();
        userManage = new javax.swing.JButton();
        userHistory = new javax.swing.JButton();
        userSearchSort = new javax.swing.JButton();
        userSideLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1108, 612));

        userParentPanel.setBackground(new java.awt.Color(255, 204, 0));
        userParentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));
        userParentPanel.setPreferredSize(new java.awt.Dimension(890, 600));

        javax.swing.GroupLayout userParentPanelLayout = new javax.swing.GroupLayout(userParentPanel);
        userParentPanel.setLayout(userParentPanelLayout);
        userParentPanelLayout.setHorizontalGroup(
            userParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        userParentPanelLayout.setVerticalGroup(
            userParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        userSidePanel.setBackground(new java.awt.Color(51, 51, 255));
        userSidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 3));
        userSidePanel.setPreferredSize(new java.awt.Dimension(220, 600));
        userSidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mcUserLogo.setFont(new java.awt.Font("STXinwei", 1, 24)); // NOI18N
        mcUserLogo.setText("Movie Collection");
        userSidePanel.add(mcUserLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        manageUserLogo.setFont(new java.awt.Font("STXinwei", 1, 20)); // NOI18N
        manageUserLogo.setText("MANAGEMENT");
        userSidePanel.add(manageUserLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        systemUserLogo.setFont(new java.awt.Font("STXinwei", 1, 20)); // NOI18N
        systemUserLogo.setText("SYSTEM");
        userSidePanel.add(systemUserLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        userHome.setBackground(new java.awt.Color(255, 255, 0));
        userHome.setFont(new java.awt.Font("STZhongsong", 1, 18)); // NOI18N
        userHome.setText("Home");
        userHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userHomeActionPerformed(evt);
            }
        });
        userSidePanel.add(userHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, 50));

        userManage.setFont(new java.awt.Font("STZhongsong", 1, 18)); // NOI18N
        userManage.setText("Manage");
        userManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManageActionPerformed(evt);
            }
        });
        userSidePanel.add(userManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, 50));

        userHistory.setFont(new java.awt.Font("STZhongsong", 1, 18)); // NOI18N
        userHistory.setText("History");
        userHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userHistoryActionPerformed(evt);
            }
        });
        userSidePanel.add(userHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 140, 50));

        userSearchSort.setFont(new java.awt.Font("STZhongsong", 1, 16)); // NOI18N
        userSearchSort.setText("Search/Sort");
        userSearchSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSearchSortActionPerformed(evt);
            }
        });
        userSidePanel.add(userSearchSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 140, 50));

        userSideLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/side panel.png"))); // NOI18N
        userSidePanel.add(userSideLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(userSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userSidePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userHomeActionPerformed
        userHome.setBackground(Color.yellow);
        userManage.setBackground(Color.white);
        userSearchSort.setBackground(Color.white);
        userHistory.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_userHomeActionPerformed

    private void userManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManageActionPerformed
        userHome.setBackground(Color.white);
        userManage.setBackground(Color.yellow);
        userSearchSort.setBackground(Color.white);
        userHistory.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_userManageActionPerformed

    private void userHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userHistoryActionPerformed
        userHome.setBackground(Color.white);
        userManage.setBackground(Color.white);
        userSearchSort.setBackground(Color.white);
        userHistory.setBackground(Color.yellow);// TODO add your handling code here:
    }//GEN-LAST:event_userHistoryActionPerformed

    private void userSearchSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSearchSortActionPerformed
        userHome.setBackground(Color.white);
        userManage.setBackground(Color.white);
        userSearchSort.setBackground(Color.yellow);
        userHistory.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_userSearchSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel manageUserLogo;
    private javax.swing.JLabel mcUserLogo;
    private javax.swing.JLabel systemUserLogo;
    private javax.swing.JButton userHistory;
    private javax.swing.JButton userHome;
    private javax.swing.JButton userManage;
    private javax.swing.JPanel userParentPanel;
    private javax.swing.JButton userSearchSort;
    private javax.swing.JLabel userSideLogo;
    private javax.swing.JPanel userSidePanel;
    // End of variables declaration//GEN-END:variables
}
